services:
  db:
    image: mysql:8.4
    container_name: hospital-management-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: clinic1122
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinicuser
      MYSQL_PASSWORD: clinic1122
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  minio:
    image: minio/minio:RELEASE.2024-12-03T18-19-38Z
    container_name: hospital-management-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: tahir
      MINIO_ROOT_PASSWORD: Raihan12
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
    depends_on:
      - db
      - minio
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5001}
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
  minio_data:
