version: "3.9"
services:
  db:
    image: mysql:8.4
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: example-password
      MYSQL_DATABASE: clinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
    environment:
      PORT: 5001
      NODE_ENV: production
      JWT_SECRET: supersecretjwt
      JWT_EXPIRES_IN: 7d
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example-password
      DB_NAME: clinic
      DB_CONNECTION_LIMIT: 10
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: hospital-data
      MINIO_USE_SSL: "false"
      MINIO_PUBLIC_URL: 'http://localhost:9000'
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5001
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
  minio_data:
